# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6246ae98d1f0e30cd534c5275c18405d66a71b8c810f483981564ddab8d330e5a00cee116de63a713872ffe35c6e6e0a6f2e0939a843bede9a4f1521c0ab6be8

test:
  secret_key_base: 0cc6964337e3cac87f91a6ada2f372d6f795a5e1adc9aedcbb557ca398a7f8ca49c04fc7928612b3bdcdd251fcee8f8b5cd8971f2ee9c4180b8ba248fee6a22d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
